.\" Manpage for simeis-server.
.TH simeis-server 1 "23 mars 2026" "1.0" "simeis-server man page"
.SH NAME
simeis-server \- Start Simeis Server
.SH SYNOPSIS
simeis-server [OPTIONS]
.SH DESCRIPTION
simeis-server is the main executable for Simeis-server.
.SH OPTIONS
The simeis-server does not take any options by default.
.SH BUGS
No known bugs.
.SH AUTHOR
Alex. C.
