name: analyse-avancé

on:
  push:
    branches:
      - 'release/*'  
      
jobs:
  quality:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Cargo unit test
        run: make unit_test

      - name: Check Python formatting
        run: python3 tests/unit-test.py

      - name: audit rust
        run: make audit