#WILLIAM
name: deploy new release
on:
  push:
jobs:
  ssh:
    name: connexion-ssh
    runs-on: ubuntu-latest
    container:
      image: testcontainers/sshd:1.3.0
    steps:
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_WILLIAM }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: connexion ssh
        run: ssh -i "${{ secrets.SSH_WILLIAM }}" -p 22222 william@78.123.114.124
      