#WILLIAM
name: deploy new release
on:
  push:
jobs:
  ssh:
    name: connexion-ssh
    runs-on: ubuntu-latest
    steps:
    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_WILLIAM }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        echo "${{ secrets.KNOW_HOST_WILLIAM }}" >> ~/.ssh/known_hosts

    - name: get simeis.deb packages
      id: url
      run: |
        URL=$(curl -s https://api.github.com/repos/alexcmb/simeis-sdv/releases/latest \
          | grep "browser_download_url.*deb" \
          | cut -d '"' -f 4)
        FILE=$(basename $URL)          # extrait le nom du fichier depuis l'URL
        echo "deb_url=$URL" >> $GITHUB_OUTPUT
        echo "deb_file=$FILE" >> $GITHUB_OUTPUT

    # - name: Download Simeis
    #   run: curl -L -O "${{ steps.url.outputs.deb_url }}"

    # - name: transfert du Debian
    #   run: |
    #     scp -vvv -i ~/.ssh/id_rsa -P ${{ secrets.HOST_PORT }} \
    #     ${{ steps.url.outputs.deb_file }} \
    #     william@${{ secrets.HOST_IP }}:${{ steps.url.outputs.deb_file }}

    - name: Deploy
      run: |
        ssh -tt -vvv -i ~/.ssh/id_rsa -p ${{ secrets.HOST_PORT }} \
        william@${{ secrets.HOST_IP }} "\
          curl -L -O ${{ steps.url.outputs.deb_url }} && \
          sudo dpkg -i ${{ steps.url.outputs.deb_file }}"
              