name: Docker Release

on:
  push:
    branches:
      - main
      - 'release/**'



jobs:
  docker-release:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:

      - name: Build (make release)
        run: make release

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extraire la version
        id: version
        run: |
          REF="${GITHUB_REF#refs/heads/}"
          VERSION="${REF#release/}"
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"
          echo "tag=v$VERSION" >> "$GITHUB_OUTPUT"
          echo "binary=simeis-server" >> "$GITHUB_OUTPUT"

      - name: Build Docker image
        run: |
          TAG="${{ steps.version.outputs.tag }}"
          docker build -f .github/Dockerfile -t "simeis-server:${TAG}" .

      - name: Test Docker image
        run: |
          TAG="${{ steps.version.outputs.tag }}"
          docker run --rm -d -p 8080:8080 --name test-simeis "simeis-server:${TAG}"
          sleep 5
          curl -f http://localhost:8080
          docker stop test-simeis

      - name: Save Docker image
        run: |
          TAG="${{ steps.version.outputs.tag }}"
          docker image save "simeis-server:${TAG}" -o "simeis-server_${TAG}.tar"

      - name: Upload Docker image artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: simeis-server_${TAG}.tar

      - name: Login Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Tag and push Docker image
        run: |
          TAG="${{ steps.version.outputs.tag }}"
          docker tag "simeis-server:${TAG}" "${{ secrets.DOCKERHUB_USERNAME }}/simeis-server:${TAG}"
          docker push "${{ secrets.DOCKERHUB_USERNAME }}/simeis-server:${TAG}"